In [18]:
import numpy as np


In [3]:
c = numpy.array([False, False, True])

c

array([False, False,  True])

In [4]:
b = numpy.array([1, 2, 3, 4, 5], dtype=float)
b

array([1., 2., 3., 4., 5.])

In [5]:
f = numpy.arange(1, 2, 0.3, dtype=float)

In [6]:
f

array([1. , 1.3, 1.6, 1.9])

In [8]:
a = numpy.array([6, 3, -5]) 
b = numpy.array([-1, 0, 7])

In [22]:
import  scipy.spatial




In [19]:
np.linalg.norm(a, ord=2) - np.linalg.norm(b, ord=2)

1.2955324534752801

In [23]:
scipy.spatial.distance.cdist(b, a, metric='euclidean')

ValueError: XA must be a 2-dimensional array.

In [24]:
scipy.spatial.distance.cdist(a[:, numpy.newaxis], b[:, numpy.newaxis], metric='euclidean')

array([[ 7.,  6.,  1.],
       [ 4.,  3.,  4.],
       [ 4.,  5., 12.]])

In [25]:
scipy.spatial.distance.cdist(a[numpy.newaxis, :], b[numpy.newaxis, :], metric='euclidean')

array([[14.2126704]])

In [26]:
a = numpy.array([0, -1, 11])
b = numpy.array([3, 7, 2])

In [27]:
a*b

array([ 0, -7, 22])

In [28]:
0*3 -7 +22

15

In [29]:
b.dot(a)

15

In [30]:
numpy.dot(a, b)

15

In [31]:
numpy.dot(a, b) / numpy.linalg.norm(a) / numpy.linalg.norm(b)

0.1724707686818527

In [35]:
a = numpy.array([8, 10, -1, 0, 0])

In [36]:
b = a.reshape((1, 5))
b

array([[ 8, 10, -1,  0,  0]])

In [37]:
c = a[numpy.newaxis, :]

In [38]:
c

array([[ 8, 10, -1,  0,  0]])

In [40]:
d = a.reshape((5, 1))

In [41]:
d

array([[ 8],
       [10],
       [-1],
       [ 0],
       [ 0]])

In [42]:
e = a[:, numpy.newaxis]
e

array([[ 8],
       [10],
       [-1],
       [ 0],
       [ 0]])